name: CI T-Hex Garage

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build & Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Gerar Prisma Client
        run: npx prisma generate

      - name: Build do Next.js (Lint e TS Check)
        run: npm run build